spring:
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
      httpclient:
        connect-timeout: 3
logging:
  level:
    root: debug