spring:
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
        - id: delayed_hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/delayedhello
          filters:
            - name: CircuitBreaker
              args:
                name: helloCircuitBreaker
                fallbackUri: forward:/fallback
        - id: fallback_route
          uri: http://localhost:8081
          predicates:
            - Path=/fallback
      httpclient:
        response-timeout: 2s
        max-header-size: 1GB
