spring:
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
        - id: delayed_hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/delayedhello
        - id: error
          uri: http://localhost:8081
          predicates:
            - Path=/error
      httpclient:
        response-timeout: 2s
logging:
  level:
    root: debug