spring:
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/hello
        - id: delayed_hello_route
          uri: http://localhost:8081
          predicates:
            - Path=/delayedhello
          filters:
            - name: CircuitBreaker
              args:
                fallbackUri: forward:/fallback
#        - id: fallback_route
#          uri: http://localhost:8081
#          predicates:
#            - Path=/fallback

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: circuitbreakers

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 2s